### ISSUE TITLE
[cms] Resize PNGs on invoice details page

### ISSUE THREAD

**Issue by alexlyp** [decred/politeiagui#1212]
Currently PNGs are rendering at whatever resolution they are uploaded which result in some huge images that can't be fully seen.

They should scale down to the screen width.

**Comment by victorgcramos** [comment]
This diff from #1218 should fix it: https://github.com/decred/politeiagui/blob/0bf469d6ef0150abf46b45cd62274d00b57bfc5b/src/style/index.css#L234-L235

**Comment by fernandoabolafio** [comment]
@victorgcramos no, it doesn't fix it. This issue needs to be addressed as soon as possible as large files are making the screen content larger than the viewport creating a horizontal scroll for the entire screen:
![May-29-2019 07-52-44](https://user-images.githubusercontent.com/14864439/58532832-0acac480-81e7-11e9-8fb0-cd1ff9ffcdf1.gif)

**Comment by victorgcramos** [comment]
Now I guess It's fixed

https://github.com/decred/politeiagui/blob/4375c9e3663137dc112147129891628ff4b965fa/src/style/index.css#L428

> @victorgcramos no, it doesn't fix it. It introduced another issue in the proposal details page in fact. Please, see the review in the Pull request.

**Comment by victorgcramos** [comment]
Sorry, I made a mistake... Now, this should fix:

https://github.com/decred/politeiagui/blob/4375c9e3663137dc112147129891628ff4b965fa/src/style/index.css#L428
