### ISSUE TITLE
[cms] Megabytes of data fetched on Account views

### ISSUE THREAD

**Issue by xaur** [decred/politeiagui#2199]
On Account > Manage Contractor tab I see 3 requests to `/api/v1/proposals/batch` fetching a total of 3.2 _megabytes_ of data (2.3 MB compressed). I guess it is the entire proposals database.

Same happens on Owned Proposals tab.

As a user, all I see that is needed on these views are IDs and titles of my owned proposals.

I'm not sure if it's solely a frontend or backend issue, or both, hence submitting to politeiagui.

**Comment by victorgcramos** [comment]
This is fixed on #2198. We can avoid the call for all approved proposals on the user view, and only do it on edit mode.

**Comment by xaur** [comment]
@victorgcramos on the Manage Contractor tab, delaying the large request until the edit mode sounds reasonable.

What about large request on Owned Proposals tab? I think it needs to fetch tokens and titles of owned proposals, perhaps something else.

**Comment by xaur** [comment]
@victorgcramos this is not fixed, I still get a 2.5 MB fetch on Owned Proposals tab.

**Comment by xaur** [comment]
This might have been fixed by #2221, not sure.

**Comment by xaur** [comment]
Ok I see only 13K fetched even when opening my proposal. Thanks for the fix, this is really closed now.
